queries = [
    "kdjalksjdalkjd [POI]",
    "N17 [GEO]",
    "tesco extra [POI]",
    "boots [POI]",
    "costa [POI] coffee [FOOD]",
    "greggs [POI]",
    "pizza hut [POI]",
    "waitrose [POI]",
    "sainsburys local [POI]",
    "burger king [POI]",
    "caffe nero [POI]",
    "london [GEO]",
    "mcdonalds [POI]",
    "starbucks [POI]",
    "restaurant [CAT]",
    "near me [PROX]",
    "16 high street oxford ox1 4ag [GEO]",
    "32 deansgate manchester m3 4lq [GEO]",
    "14 station road cambridge [GEO]",
    "27 the shambles york yo1 7lz [GEO]",
    "12 church lane leeds [GEO]",
    "3 market place norwich nr2 1nd [GEO]",
    "21 kings road brighton [GEO]",
    "nearest [PROX] petrol station [CAT]",
    "47 tavistock road london n1 [GEO]",
    "bella italia [POI] restaurant [CAT] high street manchester [GEO]",
    "costa coffee drive thru [POI] restaurant [CAT] near [PROX] camden high street [GEO]",
    "sainsburys [POI] supermarket [CAT] in [PROX] brighton [GEO]",
    "five guys [POI] burgers [FOOD] restaurant [CAT] near [PROX] oxford [GEO]",
    "closest [PROX] tesco [POI] in [PROX] plymouth [GEO]",
    "nandos [POI] chicken [FOOD] restaurant [CAT] in [PROX] birmingham [GEO]",
    "kfc [POI] fried chicken [FOOD] restaurant [CAT] nearest [PROX] bradford [GEO]",
    "wagamama [POI] ramen [FOOD] restaurant [CAT] in [PROX] covent garden [GEO]",
    "greggs [POI] bakery [CAT] near [PROX] newcastle [GEO]",
    "pizzaexpress [POI] pizza [FOOD] restaurant [CAT] in [PROX] sheffield [GEO]",
    "starbucks [POI] coffee shop [FOOD] near me [PROX]",
    "nearest [PROX] dentist [CAT] in [PROX] norwich [GEO]",
    "boots [POI] pharmacy [CAT] near [PROX] leicester [GEO]",
    "burger king [POI] fast food restaurant [CAT] closest [PROX] southampton [GEO]",
    "subway [POI] sandwiches [FOOD] restaurant [CAT] in [PROX] exeter [GEO]",
    "dominos [POI] pizza [FOOD] in [PROX] sheffield [GEO]",
    "nearest [PROX] train station [CAT] in [PROX] liverpool [GEO]",
    "primark [POI] store [CAT] in [PROX] nottingham [GEO]",
    "closest [PROX] sushi [FOOD] restaurant [CAT] in [PROX] canterbury [GEO]",
    "mcdonalds [POI] fast food restaurant [CAT] in [PROX] blackpool [GEO]",
    "aldi [POI] supermarket [CAT] near [PROX] derby [GEO]",
    "morrisons [POI] supermarket [CAT] in [PROX] bolton [GEO]",
    "pizza hut [POI] pizza [FOOD] restaurant [CAT] nearest [PROX] wakefield [GEO]",
    "closest [PROX] petrol station [CAT] near me [PROX]",
    "nearest [PROX] pub [CAT] in [PROX] windsor [GEO]",
    "thai [FOOD] food restaurant [CAT] in [PROX] reading [GEO]",
    "closest [PROX] chinese [FOOD] in [PROX] leeds [GEO]",
    "the shard [POI] in [PROX] london bridge [GEO]",
    "closest [PROX] museum [CAT] in [PROX] bristol [GEO]",
    "harrods [POI] department store [CAT] in [PROX] knightsbridge [GEO]",
    "closest [PROX] football stadium [CAT] in [PROX] manchester [GEO]",
    "the ivy [POI] restaurant [CAT] in [PROX] cheltenham [GEO]",
    "zizzi [POI] italian [FOOD] restaurant [CAT] nearest [PROX] chester [GEO]",
    "closest [PROX] fish and chips [FOOD] in [PROX] whitby [GEO]",
    "cinema [CAT] in [PROX] leicester [GEO]",
    "closest [PROX] hospital [CAT] near me [PROX]",
    "waterstones [POI] in [PROX] cambridge [GEO]",
    "nearest [PROX] tourist information centre [POI] in [PROX] oxford [GEO]",
    "lego [POI] store [CAT] in [PROX] london [GEO]",
    "zoo [CAT] in [PROX] london [GEO]",
    "mcdonalds [POI] in [PROX] stratford [GEO]",
    "tube station [CAT] near [PROX] leicester square [GEO]",
    "hotel [CAT] close to [PROX] brighton [GEO] peer [POI]",
    "yo sushi [POI] restaurant [CAT] in [PROX] london [GEO]",
    "burger [FOOD] restaurant [CAT] in [PROX] leicester [GEO]",
    "italian [FOOD] restaurant [CAT] in [PROX] chester [GEO]"
]
